import createClient from 'openapi-fetch';
import type { paths } from './v1'; // Generated by openapi-typescript
import { useAuthStore } from '../store/auth.store';

export const api = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api/v1',
});

let refreshPromise: Promise<string | null> | null = null;

const authInterceptor = {
  onRequest({ request }: { request: Request }) {
    const accessToken = useAuthStore.getState().accessToken;
    if (accessToken) {
      request.headers.set('Authorization', `Bearer ${accessToken}`);
    }
    // ensure credentials are sent for cookies (refresh token)
    if (!request.credentials || request.credentials === 'same-origin') {
      // Fetch constructor might default to same-origin, override it to include for cross-origin if needed
      // Actually 'include' is needed for refresh cookies
    }
    // We just manually construct request with credentials: 'include' when calling api.
    // openapi-fetch automatically applies credentials to fetch if we pass it, but interceptor cannot easily mutate request.credentials since it's readonly on Request object.
    // Wait, Request object properties are readonly, we can only clone it if we want to change credentials!
    // But since openapi-fetch `createClient` allows default options, we can set it there.
    return request;
  },

  async onResponse({ request, response }: { request: Request; response: Response }) {
    if (response.status === 401) {
      // Avoid infinite loops: check if this was already retried
      const isRetry = request.headers.has('X-Retry');
      if (isRetry) {
        // Hard failure: refresh failed or the token is still rejected
        useAuthStore.getState().clearAuth();
        if (typeof window !== 'undefined') {
          window.location.assign('/login');
        }
        return response;
      }

      if (!refreshPromise) {
        refreshPromise = (async () => {
          try {
            // Call the refresh endpoint directly with fetch to avoid interceptor loop
            const refreshUrl = `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api/v1'}/auth/refresh`;
            const res = await fetch(refreshUrl, {
              method: 'POST',
              credentials: 'include',
              headers: { 'Content-Type': 'application/json' },
            });
            if (!res.ok) throw new Error('Refresh failed');
            const data = await res.json();
            const newAccessToken = data.data.accessToken;
            
            // update state (keep existing user if present, or null)
            const currentUser = useAuthStore.getState().user;
            if (currentUser) {
              useAuthStore.getState().setAuth(newAccessToken, currentUser);
            } else {
              // Edge case: if we refresh but have no user, we might need a /me endpoint or similar, 
              // but for now just set token.
              useAuthStore.getState().setAuth(newAccessToken, null as any); 
            }
            return newAccessToken;
          } catch (error) {
            return null;
          } finally {
            refreshPromise = null;
          }
        })();
      }

      const newAccessToken = await refreshPromise;

      if (newAccessToken) {
        // Clone request, add retry header, update auth, and resend
        const newReq = new Request(request, {
          headers: new Headers(request.headers),
        });
        newReq.headers.set('Authorization', `Bearer ${newAccessToken}`);
        newReq.headers.set('X-Retry', 'true');
        
        const newResponse = await fetch(newReq);
        if (newResponse.status === 401) {
          useAuthStore.getState().clearAuth();
          if (typeof window !== 'undefined') {
            window.location.assign('/login');
          }
        }
        return newResponse;
      } else {
        // Refresh failed completely
        useAuthStore.getState().clearAuth();
        if (typeof window !== 'undefined') {
          window.location.assign('/login');
        }
      }
    }
    
    return response;
  }
};

api.use(authInterceptor);

// Create a helper to set credentials globally
export const apiFetch = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api/v1',
  fetch: (url, init) => {
    return fetch(url, { ...init, credentials: 'include' });
  }
});

// Apply interceptor to the helper
apiFetch.use(authInterceptor);

export const getApiClient = async () => apiFetch;
